stages:
  get_data:
    cmd: python scripts/data.py
    deps:
      - scripts/data.py
    outs:
      - data/initial_data.csv

  fit_model:
    cmd: python scripts/fit.py
    deps:
      - scripts/fit.py
      - data/initial_data.csv
      - params.yaml
    params:
      - target_col
      - one_hot_drop
      - cat_features_names
    outs:
      - models/fitted_model.pkl

  evaluate_model:
    cmd: python scripts/evaluate.py
    deps:
      - scripts/evaluate.py
      - data/initial_data.csv
      - models/fitted_model.pkl
      - params.yaml
    params:
      - target_col
    outs:
      - cv_results/cv_res.json